// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjF1YGn7HeaNfK0i-udEcGZFAy-nk4emw',
    appId: '1:243880766650:web:12ede42d7057bd672c6683',
    messagingSenderId: '243880766650',
    projectId: 'ourfoodieapp',
    authDomain: 'ourfoodieapp.firebaseapp.com',
    storageBucket: 'ourfoodieapp.appspot.com',
    measurementId: 'G-QTH4MS3JZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxUUwq8S0ce4XwmhNRXfmEt8-QfE-Ngb4',
    appId: '1:243880766650:android:14f961ebda2cc9202c6683',
    messagingSenderId: '243880766650',
    projectId: 'ourfoodieapp',
    storageBucket: 'ourfoodieapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLmTC_03MQZgHju1ZYwCXFv4pSYP3_W9A',
    appId: '1:243880766650:ios:8fc88c50eade8c222c6683',
    messagingSenderId: '243880766650',
    projectId: 'ourfoodieapp',
    storageBucket: 'ourfoodieapp.appspot.com',
    iosBundleId: 'com.nimmalasujith.ourFoodie',
  );
}
